# Generated by Django 4.0.1 on 2022-10-30 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('CID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100)),
                ('DOB', models.DateField()),
                ('profile', models.ImageField(blank=True, default=None, null=True, upload_to='image')),
                ('Village', models.CharField(max_length=100)),
                ('Chiwog', models.CharField(max_length=100)),
                ('ThramNo', models.CharField(max_length=100)),
                ('HouseHoldNo', models.CharField(max_length=100)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('contact_number', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
