# Generated by Django 4.0.1 on 2022-10-30 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MarriageID', models.CharField(max_length=100)),
                ('Marriage_certificate', models.ImageField(null=True, upload_to='image')),
                ('status', models.BooleanField(default=False)),
                ('Spouce_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Spouce', to='movies_app.user')),
                ('YOUR_CId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Your_CID', to='movies_app.user')),
            ],
        ),
    ]
