# Generated by Django 4.0.1 on 2022-10-31 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0002_marriage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Child_name', models.CharField(max_length=255)),
                ('DOB_child', models.DateField()),
                ('birth_certificate', models.ImageField(blank=True, upload_to='birth_certificate')),
                ('status', models.BooleanField(default=False)),
                ('Marriage_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents_Marriage_ID', to='movies_app.marriage')),
            ],
        ),
    ]
