# Generated by Django 4.0.1 on 2022-11-04 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0003_childdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('Timber', 'Timber'), ('Stone', 'Stone')], max_length=45)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movies_app.user')),
            ],
        ),
    ]
