# Generated by Django 4.0.1 on 2022-11-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0004_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='pass',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
